[2023-07-17T13:15:41.412+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.data_acquisition manual__2023-07-17T13:15:32.839830+00:00 [queued]>
[2023-07-17T13:15:41.421+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.data_acquisition manual__2023-07-17T13:15:32.839830+00:00 [queued]>
[2023-07-17T13:15:41.421+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-17T13:15:41.437+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): data_acquisition> on 2023-07-17 13:15:32.839830+00:00
[2023-07-17T13:15:41.442+0000] {standard_task_runner.py:57} INFO - Started process 1284 to run task
[2023-07-17T13:15:41.445+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'data_acquisition', 'manual__2023-07-17T13:15:32.839830+00:00', '--job-id', '685', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpsia_i4e5']
[2023-07-17T13:15:41.450+0000] {standard_task_runner.py:85} INFO - Job 685: Subtask data_acquisition
[2023-07-17T13:15:41.518+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.data_acquisition manual__2023-07-17T13:15:32.839830+00:00 [running]> on host d3ee5a861c36
[2023-07-17T13:15:41.611+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='data_acquisition' AIRFLOW_CTX_EXECUTION_DATE='2023-07-17T13:15:32.839830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-17T13:15:32.839830+00:00'
[2023-07-17T13:16:38.481+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/wikipedia/wikipedia.py:389 GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 389 of the file /home/***/.local/lib/python3.7/site-packages/wikipedia/wikipedia.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.
[2023-07-17T13:16:38.503+0000] {logging_mixin.py:150} INFO - Could not load Casp
[2023-07-17T13:16:59.522+0000] {logging_mixin.py:150} INFO - Could not load Computer Vision
[2023-07-17T13:17:11.334+0000] {logging_mixin.py:150} INFO - Could not load Dbscan
[2023-07-17T13:17:14.860+0000] {logging_mixin.py:150} INFO - Could not load Data Mining
[2023-07-17T13:18:15.409+0000] {logging_mixin.py:150} INFO - Could not load Github
[2023-07-17T13:18:21.027+0000] {logging_mixin.py:150} INFO - Could not load Google
[2023-07-17T13:18:44.166+0000] {logging_mixin.py:150} INFO - Could not load Identity Matrix
[2023-07-17T13:19:30.149+0000] {logging_mixin.py:150} INFO - Could not load Machine Learning
[2023-07-17T13:19:52.084+0000] {logging_mixin.py:150} INFO - Could not load Multilayer Perceptron
[2023-07-17T13:19:54.612+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-07-17T13:19:54.614+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 1284. PIDs of all processes in the group: [1284]
[2023-07-17T13:19:54.615+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 1284
[2023-07-17T13:19:54.615+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-17T13:19:54.615+0000] {logging_mixin.py:150} INFO - Could not load Np-Hard
[2023-07-17T13:19:56.384+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
