[2023-07-16T13:28:01.152+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.install_libraries manual__2023-07-16T13:28:00.348347+00:00 [queued]>
[2023-07-16T13:28:01.163+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.install_libraries manual__2023-07-16T13:28:00.348347+00:00 [queued]>
[2023-07-16T13:28:01.163+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-16T13:28:01.177+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): install_libraries> on 2023-07-16 13:28:00.348347+00:00
[2023-07-16T13:28:01.182+0000] {standard_task_runner.py:57} INFO - Started process 649 to run task
[2023-07-16T13:28:01.185+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'install_libraries', 'manual__2023-07-16T13:28:00.348347+00:00', '--job-id', '499', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmppbe3_m7r']
[2023-07-16T13:28:01.188+0000] {standard_task_runner.py:85} INFO - Job 499: Subtask install_libraries
[2023-07-16T13:28:01.232+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.install_libraries manual__2023-07-16T13:28:00.348347+00:00 [running]> on host e866793b1059
[2023-07-16T13:28:01.323+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='install_libraries' AIRFLOW_CTX_EXECUTION_DATE='2023-07-16T13:28:00.348347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-16T13:28:00.348347+00:00'
[2023-07-16T13:28:01.324+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-16T13:28:01.324+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip install networkx matplotlib']
[2023-07-16T13:28:01.335+0000] {subprocess.py:86} INFO - Output:
[2023-07-16T13:28:02.040+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-07-16T13:28:02.204+0000] {subprocess.py:93} INFO - Requirement already satisfied: networkx in /home/***/.local/lib/python3.7/site-packages (2.6.3)
[2023-07-16T13:28:02.205+0000] {subprocess.py:93} INFO - Requirement already satisfied: matplotlib in /home/***/.local/lib/python3.7/site-packages (3.5.3)
[2023-07-16T13:28:02.232+0000] {subprocess.py:93} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (0.11.0)
[2023-07-16T13:28:02.233+0000] {subprocess.py:93} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (4.38.0)
[2023-07-16T13:28:02.234+0000] {subprocess.py:93} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (1.4.4)
[2023-07-16T13:28:02.235+0000] {subprocess.py:93} INFO - Requirement already satisfied: numpy>=1.17 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (1.21.6)
[2023-07-16T13:28:02.235+0000] {subprocess.py:93} INFO - Requirement already satisfied: packaging>=20.0 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (21.3)
[2023-07-16T13:28:02.236+0000] {subprocess.py:93} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (9.5.0)
[2023-07-16T13:28:02.237+0000] {subprocess.py:93} INFO - Requirement already satisfied: pyparsing>=2.2.1 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (3.1.0)
[2023-07-16T13:28:02.238+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil>=2.7 in /home/***/.local/lib/python3.7/site-packages (from matplotlib) (2.8.2)
[2023-07-16T13:28:02.282+0000] {subprocess.py:93} INFO - Requirement already satisfied: typing-extensions in /home/***/.local/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (4.7.1)
[2023-07-16T13:28:02.306+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
[2023-07-16T13:28:07.034+0000] {subprocess.py:93} INFO - 
[2023-07-16T13:28:07.034+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.1.2 -> 23.2
[2023-07-16T13:28:07.034+0000] {subprocess.py:93} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-07-16T13:28:07.192+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-16T13:28:07.235+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=install_libraries, execution_date=20230716T132800, start_date=20230716T132801, end_date=20230716T132807
[2023-07-16T13:28:07.265+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-16T13:28:07.296+0000] {taskinstance.py:2653} INFO - 2 downstream tasks scheduled from follow-on schedule check
