[2023-07-17T13:37:08.619+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.install_libraries manual__2023-07-17T13:37:07.226447+00:00 [queued]>
[2023-07-17T13:37:08.628+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.install_libraries manual__2023-07-17T13:37:07.226447+00:00 [queued]>
[2023-07-17T13:37:08.628+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-17T13:37:08.642+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): install_libraries> on 2023-07-17 13:37:07.226447+00:00
[2023-07-17T13:37:08.647+0000] {standard_task_runner.py:57} INFO - Started process 615 to run task
[2023-07-17T13:37:08.649+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'install_libraries', 'manual__2023-07-17T13:37:07.226447+00:00', '--job-id', '692', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpm9dcezfe']
[2023-07-17T13:37:08.653+0000] {standard_task_runner.py:85} INFO - Job 692: Subtask install_libraries
[2023-07-17T13:37:08.696+0000] {task_command.py:410} INFO - Running <TaskInstance: main_dag.install_libraries manual__2023-07-17T13:37:07.226447+00:00 [running]> on host 46d66aa08365
[2023-07-17T13:37:08.798+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='install_libraries' AIRFLOW_CTX_EXECUTION_DATE='2023-07-17T13:37:07.226447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-17T13:37:07.226447+00:00'
[2023-07-17T13:37:08.800+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-17T13:37:08.801+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip install networkx matplotlib scipy seaborn wikipedia graph-tool']
[2023-07-17T13:37:08.812+0000] {subprocess.py:86} INFO - Output:
[2023-07-17T13:37:09.628+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-07-17T13:37:09.818+0000] {subprocess.py:93} INFO - Requirement already satisfied: networkx in /home/***/.local/lib/python3.7/site-packages (2.6.3)
[2023-07-17T13:37:09.819+0000] {subprocess.py:93} INFO - Requirement already satisfied: matplotlib in /home/***/.local/lib/python3.7/site-packages (3.5.3)
[2023-07-17T13:37:09.819+0000] {subprocess.py:93} INFO - Requirement already satisfied: scipy in /home/***/.local/lib/python3.7/site-packages (1.7.3)
[2023-07-17T13:37:09.819+0000] {subprocess.py:93} INFO - Requirement already satisfied: seaborn in /home/***/.local/lib/python3.7/site-packages (0.12.2)
[2023-07-17T13:37:09.820+0000] {subprocess.py:93} INFO - Requirement already satisfied: wikipedia in /home/***/.local/lib/python3.7/site-packages (1.4.0)
[2023-07-17T13:37:10.018+0000] {subprocess.py:93} INFO - ERROR: Could not find a version that satisfies the requirement graph-tool (from versions: none)
[2023-07-17T13:37:10.018+0000] {subprocess.py:93} INFO - ERROR: No matching distribution found for graph-tool
[2023-07-17T13:37:10.034+0000] {subprocess.py:93} INFO - 
[2023-07-17T13:37:10.034+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.1.2 -> 23.2
[2023-07-17T13:37:10.035+0000] {subprocess.py:93} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-07-17T13:37:10.133+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-17T13:37:10.146+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-17T13:37:10.151+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=main_dag, task_id=install_libraries, execution_date=20230717T133707, start_date=20230717T133708, end_date=20230717T133710
[2023-07-17T13:37:10.166+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 692 for task install_libraries (Bash command failed. The command returned a non-zero exit code 1.; 615)
[2023-07-17T13:37:10.188+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-17T13:37:10.221+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
